# Generated by Django 4.1.13 on 2024-06-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='Common_Health_Probles',
            new_name='Common_Health_Problems',
        ),
    ]
