# Generated by Django 4.1.13 on 2024-06-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_rename_common_health_probles_dog_common_health_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(default='static/dog_image/dog_images.png', upload_to='static/dog_image/'),
        ),
    ]
