# Generated by Django 4.2 on 2025-01-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0003_dog_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dog",
            old_name="Breed",
            new_name="breed",
        ),
        migrations.RenameField(
            model_name="dog",
            old_name="Color_of_Eyes",
            new_name="color_of_eyes",
        ),
        migrations.RenameField(
            model_name="dog",
            old_name="Country_of_Origin",
            new_name="country_of_origin",
        ),
        migrations.RenameField(
            model_name="dog",
            old_name="Fur_Color",
            new_name="fur_color",
        ),
        migrations.RenameField(
            model_name="dog",
            old_name="Height_inches",
            new_name="height_inches",
        ),
        migrations.RenameField(
            model_name="dog",
            old_name="Longevity_yrs",
            new_name="longevity_yrs",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="Character_Traits",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="Common_Health_Problems",
        ),
        migrations.AlterField(
            model_name="dog",
            name="image",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="HealthProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("health_problem", models.TextField()),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_problems",
                        to="mypage.dog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trait", models.CharField(max_length=100)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_traits",
                        to="mypage.dog",
                    ),
                ),
            ],
        ),
    ]
