# Generated by Django 5.2 on 2025-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0004_rename_breed_dog_breed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="image",
            field=models.ImageField(upload_to="dog_image"),
        ),
    ]
